### ISSUE TITLE
OSX 10.14.5 - TexturedCube fails to build

### ISSUE THREAD

**Issue by roncli** [mellinoe/veldrid-samples#13]
I'm attempting to build and run the samples.  The only sample unable to be built is TexturedCube/TexturedCube.Desktop.

I'm on OSX 10.14.5, and am running this in Visual Studio for Mac 8.1.3.  I'm curious on whether this is something I can fix.

Here is the output from `dotnet build`:

```
$ dotnet build

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 6.04 sec for /Users/roncli/dev/git/github/veldrid-samples/src/SampleBase/SampleBase.csproj.
  Restore completed in 6.04 sec for /Users/roncli/dev/git/github/veldrid-samples/src/AssetPrimitives/AssetPrimitives.csproj.
  Restore completed in 6.04 sec for /Users/roncli/dev/git/github/veldrid-samples/src/TexturedCube/Application/TexturedCube.csproj.
  Restore completed in 6.45 sec for /Users/roncli/dev/git/github/veldrid-samples/src/AssetProcessor/AssetProcessor.csproj.
  Restore completed in 90.86 ms for /Users/roncli/dev/git/github/veldrid-samples/src/TexturedCube/Desktop/TexturedCube.Desktop.csproj.
  AssetPrimitives -> /Users/roncli/dev/git/github/veldrid-samples/bin/Debug/AssetPrimitives/netstandard2.0/AssetPrimitives.dll
  AssetProcessor -> /Users/roncli/dev/git/github/veldrid-samples/bin/Debug/AssetProcessor/netcoreapp2.0/AssetProcessor.dll
  SampleBase -> /Users/roncli/dev/git/github/veldrid-samples/bin/Debug/SampleBase/netstandard2.0/SampleBase.dll
  Executing: dotnet /Users/roncli/dev/git/github/veldrid-samples/bin/Debug/AssetProcessor/netcoreapp2.0/AssetProcessor.dll /Users/roncli/dev/git/github/veldrid-samples/bin/obj/TexturedCube//ProcessedAssets /Users/roncli/dev/git/github/veldrid-samples/assets/sponza/spnza_bricks_a_diff.png
  Processing /Users/roncli/dev/git/github/veldrid-samples/assets/sponza/spnza_bricks_a_diff.png
  
  Unhandled Exception: System.MissingMethodException: Method not found: 'System.Span`1<!!1> System.MemoryExtensions.NonPortableCast(System.Span`1<!!0>)'.
     at SixLabors.ImageSharp.Memory.ArrayPoolMemoryManager.Buffer`1.get_Span()
     at SixLabors.ImageSharp.Image.<>c__DisplayClass0_0.<InternalDetectFormat>b__0(IImageFormatDetector x)
     at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
     at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
     at SixLabors.ImageSharp.Image.InternalDetectFormat(Stream stream, Configuration config)
     at SixLabors.ImageSharp.Image.DiscoverDecoder(Stream stream, Configuration config, IImageFormat& format)
     at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
     at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
     at SixLabors.ImageSharp.Image.Load(Stream stream)
     at AssetProcessor.ImageSharpProcessor.ProcessT(Stream stream, String extension) in /Users/roncli/dev/git/github/veldrid-samples/src/AssetProcessor/ImageSharpProcessor.cs:line 20
     at AssetProcessor.BinaryAssetProcessor`1.Process(Stream stream, String extension) in /Users/roncli/dev/git/github/veldrid-samples/src/AssetProcessor/BinaryAssetProcessor.cs:line 12
     at AssetProcessor.Program.Main(String[] args) in /Users/roncli/dev/git/github/veldrid-samples/src/AssetProcessor/Program.cs:line 56
  /var/folders/9b/l353_dns6436_tfzxftwdgs80000gn/T/tmp1603823aada045b3a3bbf1c3fd84ce1e.exec.cmd: line 2: 48639 Abort trap: 6           dotnet /Users/roncli/dev/git/github/veldrid-samples/bin/Debug/AssetProcessor/netcoreapp2.0/AssetProcessor.dll /Users/roncli/dev/git/github/veldrid-samples/bin/obj/TexturedCube//ProcessedAssets /Users/roncli/dev/git/github/veldrid-samples/assets/sponza/spnza_bricks_a_diff.png
/Users/roncli/dev/git/github/veldrid-samples/Directory.Build.targets(13,5): error MSB3073: The command "dotnet /Users/roncli/dev/git/github/veldrid-samples/bin/Debug/AssetProcessor/netcoreapp2.0/AssetProcessor.dll /Users/roncli/dev/git/github/veldrid-samples/bin/obj/TexturedCube//ProcessedAssets /Users/roncli/dev/git/github/veldrid-samples/assets/sponza/spnza_bricks_a_diff.png" exited with code 134. [/Users/roncli/dev/git/github/veldrid-samples/src/TexturedCube/Application/TexturedCube.csproj]

Build FAILED.

/Users/roncli/dev/git/github/veldrid-samples/Directory.Build.targets(13,5): error MSB3073: The command "dotnet /Users/roncli/dev/git/github/veldrid-samples/bin/Debug/AssetProcessor/netcoreapp2.0/AssetProcessor.dll /Users/roncli/dev/git/github/veldrid-samples/bin/obj/TexturedCube//ProcessedAssets /Users/roncli/dev/git/github/veldrid-samples/assets/sponza/spnza_bricks_a_diff.png" exited with code 134. [/Users/roncli/dev/git/github/veldrid-samples/src/TexturedCube/Application/TexturedCube.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:20.90
```

**Comment by tzachshabtay** [comment]
Which dotnet core version do you have installed (span was introduced in 2.1 I think)?

**Comment by mellinoe** [comment]
Span has always been available as a standalone/extension package, at least for .NET Core 2.0. I'll try to take a look at this sometime soon. It shouldn't be a hard fix, probably some dependency needs bumped.
