### ISSUE TITLE
Vanila VS2019 can't process TexturedCube teture

### ISSUE THREAD

**Issue by gleblebedev** [mellinoe/veldrid-samples#16]
I guess it depends on a certain version of .NET Core

1>------ Build started: Project: TexturedCube (TexturedCube\TexturedCube), Configuration: Debug Any CPU ------
1>Executing: dotnet C:\github\veldrid-samples\bin/Debug/AssetProcessor/netcoreapp2.0/AssetProcessor.dll C:\github\veldrid-samples\bin\obj\TexturedCube\/ProcessedAssets C:\github\veldrid-samples\assets\sponza\spnza_bricks_a_diff.png
1>Processing C:\github\veldrid-samples\assets\sponza\spnza_bricks_a_diff.png
1>
1>Unhandled Exception: System.MissingMethodException: Method not found: 'System.Span`1<!!1> System.MemoryExtensions.NonPortableCast(System.Span`1<!!0>)'.
1>   at SixLabors.ImageSharp.Memory.ArrayPoolMemoryManager.Buffer`1.get_Span()
1>   at SixLabors.ImageSharp.Image.<>c__DisplayClass0_0.<InternalDetectFormat>b__0(IImageFormatDetector x)
1>   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
1>   at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
1>   at SixLabors.ImageSharp.Image.InternalDetectFormat(Stream stream, Configuration config)
1>   at SixLabors.ImageSharp.Image.DiscoverDecoder(Stream stream, Configuration config, IImageFormat& format)
1>   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
1>   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func`2 action)
1>   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
1>   at SixLabors.ImageSharp.Image.Load(Stream stream)
1>   at AssetProcessor.ImageSharpProcessor.ProcessT(Stream stream, String extension) in C:\github\veldrid-samples\src\AssetProcessor\ImageSharpProcessor.cs:line 20
1>   at AssetProcessor.BinaryAssetProcessor`1.Process(Stream stream, String extension) in C:\github\veldrid-samples\src\AssetProcessor\BinaryAssetProcessor.cs:line 12
1>   at AssetProcessor.Program.Main(String[] args) in C:\github\veldrid-samples\src\AssetProcessor\Program.cs:line 56
1>C:\github\veldrid-samples\Directory.Build.targets(13,5): error MSB3073: The command "dotnet C:\github\veldrid-samples\bin/Debug/AssetProcessor/netcoreapp2.0/AssetProcessor.dll C:\github\veldrid-samples\bin\obj\TexturedCube\/ProcessedAssets C:\github\veldrid-samples\assets\sponza\spnza_bricks_a_diff.png" exited with code -532462766.
1>Done building project "TexturedCube.csproj" -- FAILED.

**Comment by gleblebedev** [comment]
C:\github\veldrid-samples>dotnet --list-sdks
2.1.801 [C:\Program Files\dotnet\sdk]
2.2.401 [C:\Program Files\dotnet\sdk]

**Comment by gleblebedev** [comment]
Worked fine after .net core 2.0 installation. So it's a low priority issue. Just needs a clear message in case the .net core is missing.

**Comment by RMSteenwijk** [comment]
Updating the ImageSharp version to 
`    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-beta0007" />
`

in the AssetProcessor project fixed that issue for me.
