### ISSUE TITLE
run sample failed in macOS 10.12.6

### ISSUE THREAD

**Issue by zhengying** [mellinoe/veldrid-samples#8]
Environment：
.net core 2.1
macOS 10.12.6

Error here:
---------------
Unhandled Exception: System.Exception: Failed to create new MTLRenderPipelineState: Function FS is using language version 2.0 which is incompatible with this OS.
   at Veldrid.MetalBindings.MTLDevice.newRenderPipelineStateWithDescriptor(MTLRenderPipelineDescriptor desc)
   at Veldrid.MTL.MTLPipeline..ctor(GraphicsPipelineDescription& description, MTLGraphicsDevice gd)
   at Veldrid.MTL.MTLResourceFactory.CreateGraphicsPipelineCore(GraphicsPipelineDescription& description)
   at Veldrid.ResourceFactory.CreateGraphicsPipeline(GraphicsPipelineDescription& description)
   at Veldrid.ResourceFactory.CreateGraphicsPipeline(GraphicsPipelineDescription description)
   at GettingStarted.Program.CreateResources() in /Users/zhengying/Downloads/veldrid-samples-master/src/GettingStarted/Program.cs:line 99
   at GettingStarted.Program.Main(String[] args) in /Users/zhengying/Downloads/veldrid-samples-master/src/GettingStarted/Program.cs:line 33

**Comment by mellinoe** [comment]
It seems that I have compiled the Metal shaders so that they are only compatible with 10.13+, on accident. I don't have a 10.12 machine to test on, but could you try changing [this line](https://github.com/mellinoe/veldrid-samples/blob/master/src/GettingStarted/Program.cs#L119) to:

```diff
-                    extension = "metallib";
+                    extension = "metal";
```

That should cause the shader files to be compiled at runtime rather than ahead of time.

**Comment by zhengying** [comment]
It's works! thanks.
